// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwu2XblOdH65dfC3Lze2hMgBKBNVZ4BXE',
    appId: '1:855344380617:web:e3078b5a78b65f0c6a6b18',
    messagingSenderId: '855344380617',
    projectId: 'todo-crdr-freylis',
    authDomain: 'todo-crdr-freylis.firebaseapp.com',
    storageBucket: 'todo-crdr-freylis.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB96IWQKBz_NVCbddIuDNKNfKOv8RuCTUo',
    appId: '1:855344380617:android:cfc4ee77386db0816a6b18',
    messagingSenderId: '855344380617',
    projectId: 'todo-crdr-freylis',
    storageBucket: 'todo-crdr-freylis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo3mrBJX3dc8MvJcsnvDk_HvFJIWdFkLs',
    appId: '1:855344380617:ios:640a44b6e2f6fe596a6b18',
    messagingSenderId: '855344380617',
    projectId: 'todo-crdr-freylis',
    storageBucket: 'todo-crdr-freylis.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo3mrBJX3dc8MvJcsnvDk_HvFJIWdFkLs',
    appId: '1:855344380617:ios:640a44b6e2f6fe596a6b18',
    messagingSenderId: '855344380617',
    projectId: 'todo-crdr-freylis',
    storageBucket: 'todo-crdr-freylis.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwu2XblOdH65dfC3Lze2hMgBKBNVZ4BXE',
    appId: '1:855344380617:web:d33552516f5772846a6b18',
    messagingSenderId: '855344380617',
    projectId: 'todo-crdr-freylis',
    authDomain: 'todo-crdr-freylis.firebaseapp.com',
    storageBucket: 'todo-crdr-freylis.appspot.com',
  );
}
